### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Blexn**

### CODE REVIEW

**Review by peculiaruc — COMMENTED** [review]
Please remove this line ->(This reminder application helps to aid the forgetful and busy with remembering to take their daily medications). it is the same as the one under it/

Update, Retrive, Delete -> the first letters should be in small letters

**Comment by Rhemi7** [comment]
This branch has conflicts, please check and resolve

**Review by peculiaruc — COMMENTED** [review]
Remove only this line-> This reminder application helps to aid the forgetful and busy with remembering to take their daily medications.

**Comment by Blexn** [comment]
> Remove only this line-> This reminder application helps to aid the forgetful and busy with remembering to take their daily medications.

i have removed it

**Pull request merged**
