### PR TITLE
added Snacked Notification

### PR DESCRIPTION
**Pull request by itfidele**
Added Snacked Notification on **addreminders** page

### CODE REVIEW

**Comment by itfidele** [comment]
seems we are using different versions check that too to prevent some conflict

**Comment by Rhemi7** [comment]
Conflict with branch, please check and resolve

**Comment by itfidele** [comment]
What is the problem!??

**Comment by Rhemi7** [comment]
There are conflicting files in the branch, create the PR again

**Comment by itfidele** [comment]
okey let me do it

**Pull request closed without merging**
